// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	aboutPage: NamespaceAboutPageTranslation,
	homePage: NamespaceHomePageTranslation,
	profilePage: NamespaceProfilePageTranslation
}

type RootTranslation = {
	common: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * A​b​o​u​t
		 */
		about: string
	}
}

export type NamespaceAboutPageTranslation = {
	/**
	 * H​e​y​,​ ​t​h​i​s​ ​i​s​ ​a​b​o​u​t​ ​p​a​g​e
	 */
	heyFromAboutPage: string
}

export type NamespaceHomePageTranslation = {}

export type NamespaceProfilePageTranslation = {
	/**
	 * U​s​e​r
	 */
	user: string
}

export type Namespaces =
	| 'aboutPage'
	| 'homePage'
	| 'profilePage'

type DisallowNamespaces = {
	/**
	 * reserved for 'aboutPage'-namespace\
	 * you need to use the `./aboutPage/index.ts` file instead
	 */
	aboutPage?: "[typesafe-i18n] reserved for 'aboutPage'-namespace. You need to use the `./aboutPage/index.ts` file instead."

	/**
	 * reserved for 'homePage'-namespace\
	 * you need to use the `./homePage/index.ts` file instead
	 */
	homePage?: "[typesafe-i18n] reserved for 'homePage'-namespace. You need to use the `./homePage/index.ts` file instead."

	/**
	 * reserved for 'profilePage'-namespace\
	 * you need to use the `./profilePage/index.ts` file instead
	 */
	profilePage?: "[typesafe-i18n] reserved for 'profilePage'-namespace. You need to use the `./profilePage/index.ts` file instead."
}

export type TranslationFunctions = {
	common: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * About
		 */
		about: () => LocalizedString
	}
	aboutPage: {
		/**
		 * Hey, this is about page
		 */
		heyFromAboutPage: () => LocalizedString
	}
	homePage: {
	}
	profilePage: {
		/**
		 * User
		 */
		user: () => LocalizedString
	}
}

export type Formatters = {}
