// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	aboutPage: NamespaceAboutPageTranslation,
	profilePage: NamespaceProfilePageTranslation
}

type RootTranslation = {
	common: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * A​b​o​u​t
		 */
		about: string
		/**
		 * P​r​o​f​i​l​e
		 */
		profile: string
	}
	homePage: {
		/**
		 * H​e​l​l​o​ ​f​r​o​m​ ​h​o​m​e​ ​p​a​g​e​!
		 */
		hello: string
	}
}

export type NamespaceAboutPageTranslation = {
	/**
	 * H​e​y​,​ ​t​h​i​s​ ​i​s​ ​a​b​o​u​t​ ​p​a​g​e
	 */
	hello: string
}

export type NamespaceProfilePageTranslation = {
	/**
	 * U​s​e​r​ ​w​i​t​h​ ​a​n​d​ ​I​D​:​ ​{​i​d​}
	 * @param {unknown} id
	 */
	user: RequiredParams<'id'>
}

export type Namespaces =
	| 'aboutPage'
	| 'profilePage'

type DisallowNamespaces = {
	/**
	 * reserved for 'aboutPage'-namespace\
	 * you need to use the `./aboutPage/index.ts` file instead
	 */
	aboutPage?: "[typesafe-i18n] reserved for 'aboutPage'-namespace. You need to use the `./aboutPage/index.ts` file instead."

	/**
	 * reserved for 'profilePage'-namespace\
	 * you need to use the `./profilePage/index.ts` file instead
	 */
	profilePage?: "[typesafe-i18n] reserved for 'profilePage'-namespace. You need to use the `./profilePage/index.ts` file instead."
}

export type TranslationFunctions = {
	common: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * About
		 */
		about: () => LocalizedString
		/**
		 * Profile
		 */
		profile: () => LocalizedString
	}
	homePage: {
		/**
		 * Hello from home page!
		 */
		hello: () => LocalizedString
	}
	aboutPage: {
		/**
		 * Hey, this is about page
		 */
		hello: () => LocalizedString
	}
	profilePage: {
		/**
		 * User with and ID: {id}
		 */
		user: (arg: { id: unknown }) => LocalizedString
	}
}

export type Formatters = {}
